### ISSUE TITLE
Evaluation Period 1 - Week 1: Tasks

### ISSUE THREAD

**Issue by coatless** [Yashwants19/RcppMLPACK#3]
Split off from https://github.com/Yashwants19/RcppMLPACK/issues/2#issuecomment-636495013

OPEN a PR in RcppMLPACK.

- [ ] Completing R utility functions and testing of these functions in RcppMLPACK.
-- This week my main focus will be to pass matrices from/to R without creating unnecessary copies.
- [ ] Some more handwritten algorithm (with all r_util functions like Matrix_with_info)
-- Discuss with mentors whether the auto-generated .cpp and .R must look like handwritten binding or some more improvement is still required.

**Comment by coatless** [comment]
@Yashwants19 it would be great if you could create PRs against the repository instead of a single commit so that we could do a code review on new additions.

Nice work so far on the utilities! 

https://github.com/Yashwants19/RcppMLPACK/commit/ea6e7f6e39fc31b2788563aac89dc837af161c0a

/ cc @eddelbuettel @rcurtin

**Comment by Yashwants19** [comment]
I am really sorry, But I was thinking to push some commits before opening a PR. I can open a PR with a single commit only, No problem :).

>Nice work so far on the utilities!

Thank You.

**Comment by coatless** [comment]
Blog post for week 1's tasks is here: 

https://medium.com/@yashwantsingh.sngh/gsoc-journey-1st-week-at-mlpack-8574ae3c5530

Tasks were implemented in PR #6.

**Comment by Yashwants19** [comment]
Thank you for pointing this out here. :)

**Comment by Yashwants19** [comment]
Thank you for managing all the issues.

**Comment by rcurtin** [comment]
Seems to me like once #6 is merged that we can call the week a success.  Awesome work @Yashwants19! :+1:

**Comment by coatless** [comment]
Closed by #6
