### ISSUE TITLE
Evaluation Period 1: Week 4

### ISSUE THREAD

**Issue by coatless** [Yashwants19/RcppMLPACK#5]
Split off from https://github.com/Yashwants19/RcppMLPACK/issues/2#issuecomment-636495013

Write the glue code for generating automating-bindings.

-- print_cpp.cpp
-- print_R.cpp
-- All the supportive files.
 Integrate these glue code with cmake to build generating automating-bindings using:
-- generate_cpp.cpp.in
-- generate_R.cpp.in
I will follow the same approach that is followed by other bindings.

**Comment by coatless** [comment]
@Yashwants19 think you could post goals to the `Yashwants19/mlpack` repository or here for Evaluation period 2?

**Comment by Yashwants19** [comment]
Hi @coatless thank you for pointing out this, I will post the goals for Evaluation period 2.

**Comment by Yashwants19** [comment]
Hey everyone, here is the [link](https://medium.com/@yashwantsingh.sngh/gsoc-weekly-blog-7b51e8e24928) for my weekly blog. Kindly share your views.

Thank you.

**Comment by rcurtin** [comment]
Thanks, everything is looking great. :) :+1:

**Comment by Yashwants19** [comment]
Hey everyone, here is the [link](https://medium.com/@yashwantsingh.sngh/gsoc-4-5-part-2-6685cc70185d) for my weekly blog. Kindly share your views.

Thank you.
